using System.Runtime.ExceptionServices;
using TryCatchInTryCatch;


//private double first{ get; set; }
//private double second { get; set; }

//public Calc(double First, double Second)
//{

//    this.first = First;
//    this.second = Second;
//}


Calc calc = new();
calc.div();